export const DOCTOR_DETAILS_REQUEST = 'DOCTOR_DETAILS_REQUEST';
export const DOCTOR_DETAILS_SUCCESS = 'DOCTOR_DETAILS_SUCCESS';
export const DOCTOR_DETAILS_FAIL = 'DOCTOR_DETAILS_FAIL';

export const DOCTOR_UPDATE_REQUEST = 'DOCTOR_UPDATE_REQUEST';
export const DOCTOR_UPDATE_SUCCESS = 'DOCTOR_UPDATE_SUCCESS';
export const DOCTOR_UPDATE_FAIL = 'DOCTOR_UPDATE_FAIL';